/* The cheat sheet: the only sourced content in the app. Keep the citations. */
/* ============================ cheat sheet ============================ */
const SHEETS = [
{ cat: "Wide bandgap", title: "Driving SiC and GaN", rows: [
  { e: "CMTI ≥ 100 kV/µs for SiC and GaN", n: "50 kV/µs is enough for silicon. Pick a driver whose CMTI beats your actual dv/dt by at least 20 % — below that, common-mode transients corrupt the drive signal itself.", src: "onsemi AND9949" },
  { e: "active Miller clamp, or −3 to −5 V off bias", n: "Above a few volts per nanosecond, C_gd pushes the gate back up through R_g(off). A clamp sinks that current in a low-impedance path that bypasses the gate resistor entirely.", src: "Navitas AN021 · ST AN5583" },
  { e: "do not over-do negative bias on GaN", n: "There is no body diode, so reverse conduction happens at V_GS − V_th. Every extra volt of negative bias adds directly to third-quadrant loss during dead time.", src: "GaN Systems GN001" },
  { e: "clamp the bootstrap supply on GaN", n: "The switch node swings below ground during dead time, over-charging C_boot. Without a clamp near 5.75 V you exceed the gate rating on a part with almost no margin.", src: "EPC / Iron Device SMA6533" },
  { e: "P_driver = Q_g·V_drive·f_sw", n: "Independent of load power — budget it thermally per channel before you pick the package.", src: "" },
  { e: "measure V_GS at the device, Kelvin, hot", n: "Probing at the controller pin hides exactly the ringing that destroys parts.", src: "" },
]},
{ cat: "Magnetics", title: "Litz wire, done properly", rows: [
  { e: "strand diameter < δ, often by 4× or more", n: "A strand comparable to the skin depth buys almost nothing. The published design method targets a factor of several below it.", src: "Sullivan & Zhang, APEC 2014" },
  { e: "n₁(max) = 4·(δ/d_s)²  strands per bunching step", n: "With d_s = δ/4 that is 64 strands in a single twisting operation — beyond it you need a second stage or the bundle stops behaving.", src: "Sullivan & Zhang, APEC 2014" },
  { e: "bundle skin effect starts at ~2δ diameter", n: "The bundle as a whole behaves like a solid conductor once it gets large, no matter how fine the strands are.", src: "Sullivan & Zhang, APEC 2014" },
  { e: "twist ≤ 5 strands per stage", n: "Groups of five or fewer have no centre strand. A group of seven has one that is shielded by the others and carries almost nothing.", src: "Sullivan & Zhang, APEC 2014" },
  { e: "δ_eff = δ/√F_p", n: "Litz porosity: insulation displaces copper, so the effective skin depth degrades with packing factor. Finer strands cut AC resistance but raise DC resistance — there is an optimum.", src: "Sullivan, IEEE TPEL 1999" },
  { e: "first-cut window fill ≤ 25–30 % copper", n: "A realistic starting point for a litz-wound component, insulation and bobbin included.", src: "Sullivan & Zhang, APEC 2014" },
  { e: "interleave, then interleave again", n: "Splitting the primary around the secondary roughly halves the effective layer count and cuts proximity loss about fourfold per split.", src: "Erickson & Maksimović, ch. 12" },
]},
{ cat: "Magnetics", title: "Core loss you can trust", rows: [
  { e: "plain Steinmetz is for sinusoids only", n: "P_v = k·f^α·B^β assumes sinusoidal excitation. Your converter produces triangular or trapezoidal flux, and the error is not small.", src: "" },
  { e: "use iGSE for PWM flux", n: "P_v = (1/T)∫ k_i·|dB/dt|^α·(ΔB)^(β−α) dt, with k_i derived from the same k, α, β. This is the accepted state of the art among methods that need only Steinmetz parameters.", src: "Venkatachalam & Sullivan, COMPEL 2002" },
  { e: "neither captures DC bias", n: "A choke with a large DC component needs bias-dependent parameters or measured data. Do not trust a datasheet curve taken at zero bias.", src: "ETH Zürich PMSRC" },
  { e: "design against the hot curve", n: "B_sat falls roughly 20 % from 25 °C to 100 °C in power ferrite, and core loss curves shift with temperature in both directions depending on the material.", src: "" },
]},
{ cat: "Capacitors", title: "What MLCCs actually give you", rows: [
  { e: "a 10 µF 6.3 V X5R at 5 V can be under 4 µF", n: "Losses of 35–65 % under DC bias are routine for Class-II ceramics. Always check the effective value at the working voltage in the vendor simulator, never the printed number.", src: "Murata SimSurfing · KEMET K-SIM" },
  { e: "derate Class II to 50–70 % of rated voltage", n: "3.3 V rail → 6.3 V part; 5 V → 10 V; 12 V → 25 V. Across a switch node, halve it again.", src: "" },
  { e: "capacitance density trades against derating", n: "A 10 µF 0805 X7R holds more capacitance at 5 V than a 10 µF 0402 X5R. The smaller part is not the same component.", src: "" },
  { e: "DC bias accelerates ageing 5–10×", n: "Observed loss rates of 15–20 % per decade-hour under bias. Reflow above the Curie point resets the clock, which is why bench measurements on a fresh board mislead.", src: "osengr.org MLCC study" },
  { e: "Class II ceramics sing", n: "Modern coil whine is usually the capacitors, not the inductor. Smaller packages are less microphonic; soft-termination parts help.", src: "" },
  { e: "never use Class II for timing", n: "Bias, ageing, tempco and microphonics all stack. Use C0G/NP0 anywhere the value matters.", src: "" },
  { e: "electrolytic life: L = L₀·2^((T₀−T)/10)", n: "A 5000 h/105 °C part gives roughly 10 000 h at 95 °C and 20 000 h at 85 °C. The ripple-current rating is a thermal limit, not an electrical one.", src: "Nippon Chemi-Con · XP Power" },
]},
{ cat: "Snubbers", title: "Snubber design by measurement", rows: [
  { e: "1. measure f₀ · 2. add C · 3. measure f₁", n: "The two-measurement method: with a known added capacitance the frequency shift gives you both parasitics, no guessing.", src: "Nexperia AN11160" },
  { e: "add C until f halves → C_par = C_add/3", n: "The quick field version of the same thing. Then L_par = 1/((2πf₀)²·C_par).", src: "In Compliance / DigiKey" },
  { e: "R_snub = √(L_par/C_par), C_snub ≈ 3–4·C_par", n: "R equal to the characteristic impedance is the critically damped choice; anywhere from Z₀ to 2·Z₀ is usable.", src: "" },
  { e: "budget 25–60 mW and check it", n: "P = C_snub·V²·f_sw. Snubbers become hot spots faster than anyone expects, and the resistor is usually an 0603.", src: "Biricha / Shirsavar" },
  { e: "place it at the node with its own return via", n: "A snubber on the end of a long trace is an inductor with a resistor in series. It provides no damping.", src: "" },
]},
{ cat: "Layout", title: "The hot loop, precisely", rows: [
  { e: "buck: C_in → HS → LS → back to C_in", n: "This is the only loop carrying fully switched current, from zero to I_pk and back every cycle. It radiates in proportion to its area. Everything else is second order.", src: "ADI AN-139" },
  { e: "boost: switch → diode → C_out", n: "The critical loop moves to the output side. Get this wrong and the input filter cannot save you.", src: "ADI AN-139" },
  { e: "four-switch buck-boost has two hot loops", n: "Input side and output side, and both need minimising — a common cause of designs that pass at one V_in and fail at another.", src: "TI SLVAFJ3" },
  { e: "input cap negative terminal at the LS source", n: "Positive terminal at the HS drain. A via inside the hot loop adds about a nanohenry, which is volts of overshoot at 10 A/ns.", src: "TI SLVAFJ3" },
  { e: "unbroken ground plane directly beneath", n: "The image current cancels loop inductance only if the return path is unobstructed. Never route signals through it.", src: "TI SNVA638A, after Ott" },
  { e: "keep switch-node copper small", n: "It needs enough area for current and not one square millimetre more. Extra copper is a dv/dt antenna.", src: "TI SLVAFJ3" },
]},
{ cat: "Control", title: "Loop design, more precisely", rows: [
  { e: "peak current mode has a double pole at f_sw/2", n: "The sampling effect, not a parasitic. It sets the real bandwidth ceiling; inner-loop bandwidth lands around f_sw/6 to 2f_sw/3.", src: "Ridley, current-mode model" },
  { e: "keep the current-loop Q between 0.5 and 1", n: "Too little slope compensation peaks and goes subharmonic past D = 0.5; too much turns the converter back into voltage mode with extra phase lag.", src: "Ridley · TI How2Power" },
  { e: "optimal S_e equals the inductor downslope", n: "S_e ≥ 0.5·S_f is the stability minimum. Matching the downslope gives deadbeat response — one cycle to correct a perturbation.", src: "Ridley" },
  { e: "sense the output at the output capacitor", n: "Not after a second filter stage. Otherwise the loop faithfully regulates a node the load never sees.", src: "Würth DC/DC design handbook" },
  { e: "compensation components at the FB pin", n: "The error-amplifier summing node is the highest-impedance point in the converter and the easiest to inject noise into.", src: "TI SSZTAL0" },
]},
{ cat: "Numbers", title: "PFC and rectifier practice", rows: [
  { e: "PFC voltage loop 10–20 Hz, current loop kHz", n: "1 % of second-harmonic ripple on the error amplifier output produces roughly 0.5 % third-harmonic distortion in the line current.", src: "UC3854 application note" },
  { e: "CCM PFC inductor ripple 20–40 % of I_in(avg)", n: "A practical starting band before core loss or switch rms current starts to dominate.", src: "Infineon DN 2013-01" },
  { e: "≈ 100 W of PFC output per amp of diode rating", n: "First-pass sizing for the boost rectifier; add a surge-bypass diode for inrush.", src: "Infineon design guide" },
  { e: "CCM totem-pole demands zero Q_rr", n: "At each zero crossing the fast leg's duty jumps between 0 and 100 %. A silicon body diode cannot survive that commutation — this is why the topology waited for GaN and SiC.", src: "TI TIDUE54B · Infineon CoolGaN" },
  { e: "capacitor-input rectifiers: use Schade's curves", n: "Closed-form hand equations for peak repetitive diode current systematically under-predict. The 1943 curves against ωRC and source resistance remain the reference.", src: "Schade, Proc. IRE 1943" },
]},
{ cat: "Numbers", title: "Failure modes worth designing against", rows: [
  { e: "flux walking in push-pull and full bridge", n: "Any volt-second asymmetry marches the core toward one rail until it saturates. Peak current-mode control corrects it cycle by cycle; a DC-blocking capacitor helps.", src: "Pressman, Switching Power Supply Design" },
  { e: "PSFB lagging leg loses ZVS at light load", n: "The leading leg has output-inductor energy available; the lagging leg has only leakage. ½·L_r·I² ≥ (4/3)·C_oss·V_in² is the condition to check.", src: "Sabaté et al. · Rohm app note" },
  { e: "LLC below resonance is capacitive and fatal", n: "Cross into the capacitive region and the switches turn on into a charged node. Stay right of the peak-gain curve at every operating point, including start-up and short circuit.", src: "Huang, TI Power Supply Seminar" },
  { e: "DAB beyond 90° phase shift is unstable", n: "Power peaks at 90°; past it the derivative reverses sign and circulating current climbs while output power falls.", src: "Barlik et al. 2013 · De Doncker 1991" },
  { e: "check SOA, not the DC current rating", n: "The headline I_D is a bonding-wire number. Repetitive and single-pulse SOA is what actually limits a real design.", src: "" },
]},
{ cat: "Fundamentals", title: "The two balance laws", rows: [
  { e: "∫ v_L dt = 0 over one cycle", n: "Inductor volt-second balance in steady state. Every conversion ratio in this app comes from writing this for the on and off intervals." },
  { e: "∫ i_C dt = 0 over one cycle", n: "Capacitor charge balance. Use it to find average currents in transfer caps and to size ripple." },
  { e: "CCM ↔ DCM boundary: I_out = ΔI_L/2", n: "In DCM the ratio depends on load, the RHP zero disappears and the plant becomes first order." },
  { e: "ripple ratio r = ΔI_L/I_L ≈ 0.3", n: "0.2–0.4 is the practical optimum: smaller means a big inductor, larger means high peak current and core loss." },
  { e: "P = ½·L·I_pk²·f_sw", n: "Power a flyback or DCM converter can move. If the number is short, you need more L·I², i.e. a bigger core." },
]},
{ cat: "Fundamentals", title: "Choosing f_sw", rows: [
  { e: "size ∝ 1/f_sw,  loss ∝ f_sw", n: "The central trade-off. Magnetics and caps shrink; switching, gate and core losses grow." },
  { e: "avoid 455 kHz; take care from 150 kHz to 30 MHz", n: "455 kHz is the AM intermediate frequency, and the CISPR conducted range starts at 150 kHz — a 100 kHz fundamental keeps the first harmonic below it." },
  { e: "Si: ≤ 500 kHz · SiC: 100 k–500 kHz · GaN: 500 kHz–5 MHz", n: "Rough comfort zones for hard-switched hundreds of watts." },
  { e: "t_on(min) = D_min/f_sw", n: "Check against the controller's minimum on-time — this kills more high-V_in designs than anything else." },
]},
{ cat: "Magnetics", title: "Inductor design", rows: [
  { e: "L = V·Δt/ΔI", n: "Everything starts here: applied volt-seconds over the ripple you allow." },
  { e: "N = L·I_pk/(B_max·A_e)", n: "Turns for a given peak flux. Keep B_max at 0.7–0.8·B_sat hot." },
  { e: "l_gap = µ₀·N²·A_e/L", n: "Gap length for a gapped ferrite; ignores fringing, which typically adds 10–20 % to the effective A_e." },
  { e: "A_p = A_e·A_w = L·I_pk·I_rms/(K_u·J·B_max)", n: "Area product — picks the core size before you know the core. K_u ≈ 0.4, J ≈ 4–5 A/mm²." },
  { e: "E = ½·L·I²", n: "Stored energy. A gap is just a place to store it outside the ferrite." },
  { e: "P_core = k·f^α·B^β  (Steinmetz)", n: "α ≈ 1.3–1.6, β ≈ 2.3–2.7 for power ferrite. Use B_pk, not B_pk-pk, and check the datasheet curve at your temperature." },
  { e: "δ = 66/√f  mm (copper, 20 °C)", n: "Skin depth. 100 kHz → 0.21 mm, so wire thicker than ~0.4 mm diameter is wasted; use litz or foil." },
]},
{ cat: "Magnetics", title: "Core materials", rows: [
  { e: "MnZn ferrite: B_sat ≈ 390 mT hot", n: "Grades N87 and 3C95 are the usual starting points. Default for 20 kHz–1 MHz. Low loss, hard saturation — needs a discrete gap." },
  { e: "Powder iron: B_sat ≈ 1.0–1.5 T", n: "Cheap, soft saturation, high core loss. Fine for line filters, poor above ~100 kHz." },
  { e: "Sendust / Kool Mµ: B_sat ≈ 1 T", n: "Distributed gap, soft roll-off, good DC bias behaviour. The usual PFC choke material." },
  { e: "MPP: B_sat ≈ 0.75 T", n: "Lowest loss of the powder cores, most expensive. Filter and output chokes." },
  { e: "Nanocrystalline: B_sat ≈ 1.2 T, µ_r huge", n: "Common-mode chokes and high-frequency transformers." },
  { e: "derate B_sat by ~20 % at 100 °C", n: "Always design against the hot curve, not the 25 °C one." },
]},
{ cat: "Magnetics", title: "Transformer design", rows: [
  { e: "N_p = V_in·D/(f_sw·ΔB·A_e)", n: "Primary turns from volt-seconds. For a two-quadrant drive use ΔB ≈ 0.2–0.3 T, for a flyback use B_pk." },
  { e: "flyback: gap set by energy, not by ΔB", n: "The flyback transformer is a coupled inductor, not a true transformer. Size the gap so B_pk at I_pk stays below saturation." },
  { e: "L_leak ≈ 1–3 % of L_p", n: "Interleaving primary and secondary halves cuts it roughly fourfold." },
  { e: "F_r = R_ac/R_dc (Dowell)", n: "Layer count drives AC resistance far more than wire gauge. Interleave, then interleave again." },
  { e: "safety: 3 layers of tape or triple-insulated wire", n: "Reinforced insulation for mains isolation; creepage typically 6.4 mm across the barrier." },
]},
{ cat: "Capacitors", title: "Ripple and selection", rows: [
  { e: "ΔV = ΔQ/C + ESR·ΔI + ESL·di/dt", n: "Three terms. Above a few hundred kilohertz the middle one usually wins; during a load step the third one does." },
  { e: "MLCC X7R loses 50–80 % of its capacitance at rated V_dc", n: "A 10 µF 25 V X7R at 12 V may be 4 µF. Always check the DC bias curve — this is the most frequently overlooked derating in power design." },
  { e: "C_hold = 2·P·t/(V1² − V2²)", n: "Hold-up sizing for bulk caps." },
  { e: "electrolytic life doubles per 10 °C cooler", n: "Ripple current heats the core; the rms rating is a thermal limit, not an electrical one." },
  { e: "class-II ceramics are piezoelectric", n: "Audible singing on a rail with ripple in the 1–10 kHz band; use two smaller caps or film." },
  { e: "polymer / hybrid: low ESR, no dry-out", n: "Good replacement for electrolytics up to ~100 V." },
]},
{ cat: "Semiconductors", title: "MOSFET loss", rows: [
  { e: "P_cond = I_rms²·R_DS(on) at T_j", n: "R_DS(on) rises 1.3–1.7× from 25 °C to 100 °C in silicon. Always use the hot number." },
  { e: "P_sw ≈ ½·V_ds·I_d·(t_r + t_f)·f_sw", n: "Only for hard-switched transitions. Add Q_oss·V·f and Q_rr·V·f." },
  { e: "P_gate = Q_g·V_drive·f_sw", n: "Dissipated in the driver and R_g, not in the FET channel." },
  { e: "FOM = R_DS(on)·Q_g", n: "The single best figure for comparing devices at a given voltage class." },
  { e: "P_body = V_F·I·t_dead·f_sw·2", n: "Body-diode conduction during dead time; also where Q_rr comes from." },
  { e: "check SOA, not just I_D(max)", n: "The DC current rating is a bonding-wire number. Repetitive and single-pulse SOA is what actually limits you." },
]},
{ cat: "Semiconductors", title: "Which device technology", rows: [
  { e: "Si MOSFET < 250 V", n: "Cheap, fast, excellent R_DS(on)·A. The default below 100 V." },
  { e: "Superjunction 500–900 V", n: "Off-line workhorse. Nonlinear C_oss and slow body diode — avoid hard-commutating it." },
  { e: "IGBT 600 V–6.5 kV, < ~20 kHz", n: "Current-density king at high voltage and low frequency; tail current dominates switching loss." },
  { e: "SiC MOSFET 650 V–1.7 kV", n: "Replaces IGBTs when frequency or efficiency matters. Needs careful gate drive (often −3 to −5 V off)." },
  { e: "GaN HEMT 100–650 V", n: "Lowest Q_oss and zero reverse recovery; enables MHz operation and totem-pole PFC. Tight gate margins, no avalanche." },
  { e: "Schottky vs SiC diode", n: "Schottky below 200 V for zero recovery; SiC above for the same benefit." },
]},
{ cat: "Thermal", title: "Getting heat out", rows: [
  { e: "T_j = T_a + P·(R_θjc + R_θcs + R_θsa)", n: "The whole thermal design in one line. Solve for allowed P at the worst-case T_a." },
  { e: "1 oz copper pour: R_θ ≈ 50 °C/W at 1 cm²", n: "Falls to about 30 °C/W at 6 cm², then flattens. More copper past that buys little." },
  { e: "thermal via: ≈ 100 °C/W each", n: "Use arrays of 0.3 mm vias under the pad; an array of twenty provides a genuine thermal path." },
  { e: "Z_θ(t) for pulses", n: "Short overloads ride the transient impedance curve; a 10 ms pulse may see a tenth of the steady-state R_θ." },
  { e: "derate to T_j ≤ 110–125 °C", n: "Leaves margin for R_DS(on) tempco runaway and improves lifetime." },
]},
{ cat: "Control", title: "Loop shaping", rows: [
  { e: "f_c ≤ f_sw/10", n: "Sampling makes anything faster unreliable; f_sw/20 is the safe default for voltage mode." },
  { e: "phase margin 45–60°, gain margin > 10 dB", n: "Below 45° gives ringing overshoot; above 60° is sluggish." },
  { e: "voltage mode: double pole at 1/(2π√LC)", n: "Needs a Type III compensator to add the two zeros back." },
  { e: "peak current mode: single pole at 1/(2π·R·C)", n: "The inductor pole disappears, so a Type II compensator is enough." },
  { e: "slope comp S_e ≥ 0.5·S_f for D > 0.5", n: "S_f = (V_out/L)·R_i. Without it, alternate-cycle instability at high duty." },
  { e: "RHP zero: boost, buck-boost, flyback (CCM)", n: "Cross over below f_RHPZ/5. Nothing in the compensator can fix it — only lower L or DCM can." },
  { e: "ESR zero at 1/(2π·ESR·C)", n: "All-ceramic outputs push it far out, which is why they often need more compensation, not less." },
]},
{ cat: "Control", title: "Current sensing", rows: [
  { e: "shunt: accurate, lossy", n: "P = I²R. Kelvin-connect it and keep the sense pair tight and away from the switch node." },
  { e: "inductor DCR sense: lossless, drifts", n: "R·C must match L/DCR; copper drifts +0.39 %/°C, so accuracy is ±20 % unless compensated." },
  { e: "R_DS(on) sense: free, very inaccurate", n: "Fine for cycle-by-cycle limiting, not for current sharing." },
  { e: "current transformer: isolated, no DC", n: "Needs a reset winding or volt-second balance; standard on bridge primaries." },
  { e: "Hall / fluxgate: isolated, DC-capable", n: "Slow (tens of kHz) and expensive; used for output and grid current." },
]},
{ cat: "Snubbers", title: "Damping the ringing", rows: [
  { e: "1. measure f_ring with the probe at the node", n: "2. add C_test until f drops by half → C_par = C_test/3. 3. L_par = 1/((2πf)²·C_par)." },
  { e: "R_snub = √(L_par/C_par)", n: "Critical damping. C_snub ≈ 3–4× C_par." },
  { e: "P_snub = C_snub·V²·f_sw", n: "Check this before you pick the package — RC snubbers reach significant dissipation quickly." },
  { e: "RCD clamp: V_clamp ≈ 1.3–1.5·V_R", n: "Flyback. Lower is lossier, higher risks exceeding V_DS. R = V_clamp²/P_clamp." },
  { e: "ferrite bead on the diode/gate", n: "Cheapest fix for high-frequency ringing when a full snubber is overkill." },
  { e: "TVS for load dump / surge, not for ringing", n: "Repetitive clamping will overheat a TVS. It is a survival device, not a snubber." },
]},
{ cat: "Snubbers", title: "Gate drive", rows: [
  { e: "R_g controls dv/dt and EMI", n: "Split turn-on/turn-off resistors: slow on to tame recovery, fast off to cut loss." },
  { e: "C_boot ≥ Q_total/ΔV_boot", n: "Use 10–100× the minimum. Refresh needs a minimum off-time every cycle." },
  { e: "Miller clamp or −2 to −5 V off bias", n: "Above a few V/ns, C_gd re-turns-on the low-side device. This is a frequent cause of otherwise unexplained shoot-through." },
  { e: "t_dead > t_off(max) + propagation skew", n: "Then subtract as much as you dare — dead time is pure body-diode loss." },
  { e: "keep the gate loop area tiny", n: "The driver's return must go straight to the Kelvin source pin, never through the power path." },
  { e: "isolated drives: CMTI ≥ 100 kV/µs for SiC/GaN", n: "Below that, common-mode transients corrupt the drive signal." },
]},
{ cat: "Layout", title: "Layout rules that actually matter", rows: [
  { e: "minimise the hot loop area first", n: "Buck: C_in → HS → LS → back to C_in. Boost: switch → diode → C_out. Everything else is secondary." },
  { e: "put the input cap on the same layer as the FETs", n: "A via in the hot loop adds ~1 nH; that is volts of overshoot at 10 A/ns." },
  { e: "unbroken ground plane directly beneath", n: "The image current cancels the loop inductance. Never route signals through it." },
  { e: "keep the switch node copper small", n: "It only needs enough area for current — extra copper is a dv/dt antenna." },
  { e: "single-point connection for analog ground", n: "Feedback divider and compensation return to the IC ground pin, not the power ground." },
  { e: "route feedback away from the switch node and inductor", n: "Or shield it with ground. Injected noise on FB looks like a load transient to the loop." },
]},
{ cat: "Layout", title: "EMI", rows: [
  { e: "DM noise ∝ input ripple current", n: "Fixed with X caps and a DM choke, or by interleaving." },
  { e: "CM noise ∝ dv/dt × parasitic C to earth", n: "Dominated by the switch node and the transformer's interwinding capacitance." },
  { e: "Y-cap limited by leakage current", n: "Typically ≤ 4.7 nF total for 250 V AC class II. Add a transformer shield instead of more Y." },
  { e: "CM choke: L_cm 1–10 mH", n: "Place the resonance with the Y caps below 150 kHz." },
  { e: "spread spectrum yields 6–10 dB", n: "It reshapes the measurement, not the energy. It should not be used to compensate for a poor layout." },
  { e: "CISPR 32 class B: 66→56 dBµV, 150–500 kHz", n: "Class A is 13 dB looser. Pick the class before choosing f_sw." },
]},
{ cat: "Numbers", title: "Constants and rules of thumb", rows: [
  { e: "µ₀ = 4π×10⁻⁷ H/m", n: "ρ_Cu = 1.72×10⁻⁸ Ω·m at 20 °C, +0.39 %/°C." },
  { e: "1 oz copper = 35 µm", n: "Roughly 0.5 mΩ per square. External trace: 1 mm width ≈ 3 A for a 20 °C rise." },
  { e: "current density J = 4–6 A/mm²", n: "Wire in a wound component with reasonable airflow." },
  { e: "derate V: 80 % of rating", n: "MOSFET V_DS, cap voltage, diode V_R. For MLCCs across a switch node, use 50 %." },
  { e: "1 nH per mm of trace", n: "A 10 mm loop at 10 A/ns produces 100 V of overshoot. This is the mechanism behind most switch-node overshoot." },
  { e: "efficiency → loss: 95 % efficient at 100 W out = 5.3 W dissipated", n: "P_loss = P_out·(1/η − 1). Always convert to watts before designing the thermals; percentages obscure the magnitude." },
]},
];

export { SHEETS };
